### ISSUE TITLE
Seg fault while trying to ingest

### ISSUE THREAD

**Issue by stockholmux** [RediSearch/RediSearchBenchmark#2]
While attempting to run the benchmark, I keep running into seg faults. 

I'm running Redis 4.02 (OSS) / RediSearch 0.21.3 with 5 nodes. While running the benchmark using this:
```
./RediSearchBenchmark -engine redis -shards 5 -hosts "localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383"     -file ~/enwiki-latest-abstract.xml
```

I'm guessing this is a RediSearch issue, so I'll x-post an issue over on that repo.

Here are the dumps - I was pretty consistently getting 2 out of 5 shards seg faulting.

[redisearch-ingest-seg-fault2.txt](https://github.com/RedisLabs/RediSearchBenchmark/files/1400382/redisearch-ingest-seg-fault2.txt)
[redisearch-ingest-seg-fault1.txt](https://github.com/RedisLabs/RediSearchBenchmark/files/1400383/redisearch-ingest-seg-fault1.txt)

**Comment by dvirsky** [comment]
There is a bug in redis 4.0.2 that was fixed already, run it with redis unstable, it shouldn't happen.

**Comment by stockholmux** [comment]
Gotcha. I'll run it and report back.

**Comment by dvirsky** [comment]
It might be a different issue, since the benchmark doesn't do multi IIRC.
But using the latest redis is a must in this context.

**Comment by stockholmux** [comment]
Still getting seg faults in a similar pattern (run the benchmark, within a few seconds two nodes give segs, the rest run with no problem) with unstable.

Not sure if this is relevant, but I'm running the bog standard install of unstable with redis.io provided conf file and redisearch and port set via the command line when starting the servers.

[seg-fault-4.txt](https://github.com/RedisLabs/RediSearchBenchmark/files/1407144/seg-fault-4.txt)
[seg-fault-3.txt](https://github.com/RedisLabs/RediSearchBenchmark/files/1407147/seg-fault-3.txt)

I may try rolling back the versions of RediSearch until I hit one that works with the benchmark.

**Comment by stockholmux** [comment]
This must be a relatively recent bug. Unstable + RediSearch 0.20.0 and 0.21.0 do not cause seg faults.

**Comment by dvirsky** [comment]
ok, I'll try to recreate.
What are you using to run the benchmark? wikipedia extracts?

**Comment by stockholmux** [comment]
Yup. Wikipedia extracts.

**Comment by dvirsky** [comment]
@mnunberg do you mind having a look?

**Comment by mnunberg** [comment]
@stockholmux how long until the segfault is triggered. Trying to reproduce but no luck so far.

**Comment by mnunberg** [comment]
ok, I seem to have triggered it.

**Comment by mnunberg** [comment]
@stockholmux btw did you get this on Mac or Linux?

**Comment by stockholmux** [comment]
@mnunberg AWS / Ubuntu: c4.4xlarge.

**Comment by mnunberg** [comment]
I believe I've fixed the issue. Can you verify? (latest master on RediSearch)

**Comment by stockholmux** [comment]
@mnunberg I won't have a chance until Thursday, unfortunately.

**Comment by filipecosta90** [comment]
closing given this issue is no longer relevant/applicable.
